### ISSUE TITLE
Typing should not be required in python 3.7 / 3.6

### ISSUE THREAD

**Issue by s-knibbs** [dbrgn/result#12]
I'm currently experiencing issues when installing this in python 3.7 because the `typing` dependency is conflicting with the standard library typing, see python/typing#573.

Looks like the requirement just needs changing to `typing; python_version < '3.5'`

**Comment by dbrgn** [comment]
Interesting, since we run tests on Python 3.7 in CI: https://travis-ci.org/dbrgn/result

**Comment by dbrgn** [comment]
I tried adding `python setup.py install` to CI in #13, seems to have worked. But I guess excluding the dependency on Python 3.6+ shouldn't hurt!
