### ISSUE TITLE
Good time for 0.4.1 release?

### ISSUE THREAD

**Issue by francium** [dbrgn/result#22]
Getting a `mypy` error when I try to use tihs at the `0.4.0` release.
```
u86asm.py:10: error: Cannot find implementation or library stub for module named 'result'
u86asm.py:10: note: See https://mypy.readthedocs.io/en/latest/running_mypy.html#missing-imports
```

I believe the `py.typed` file added in #16 solves this issue. I didn't have any issue when I installed github master version as opposed to the pipy `0.4.0` release.

Maybe we can bump to `0.5.0` if we can merge #19 and get the new methods in.

**Comment by dbrgn** [comment]
Good point, I'll release `0.4.1`.

**Comment by dbrgn** [comment]
Version 0.4.1. is released on PyPI.
