### ISSUE TITLE
Release 0.5.0

### ISSUE THREAD

**Issue by dbrgn** [dbrgn/result#25]
I would suggest to release version 0.5.0 (including #8 and #11) soon and to defer #17/#18 for a future version.

Do you agree, @francium?

**Comment by francium** [comment]
Yes

**Comment by francium** [comment]
Do you want to wait some more for #11's author to respond or should get it finished ourselves?

**Comment by dbrgn** [comment]
@francium if you feel like it, you can take over that PR!

I think it should be even possible to resolve the conflict directly on GitHub:

![2020-03-02-105137_684x227_scrot](https://user-images.githubusercontent.com/105168/75665043-cedff680-5c73-11ea-85a0-eb265dc2aede.png)

**Comment by dbrgn** [comment]
Version 0.5.0 is now published.

I also noticed that the `py.typed` file was not included in the dist previously. I fixed that using a [`MANIFEST.in`](https://github.com/dbrgn/result/blob/master/MANIFEST.in) file.
