### ISSUE TITLE
Please add more Result methods

### ISSUE THREAD

**Issue by wizzardx** [dbrgn/result#3]
So that eg, we can use these:

eg: Return result if not an error, otherwise raise a fairly generic exception:

x = result.unwrap()

eg: Return result if not an error, otherwise raise an exception with a specific description:

x = result.expect("Unable to initialise subsystem!")

Basically please, a lot more of the methods supported by Rust Results, in terms of methods:

https://doc.rust-lang.org/std/result/enum.Result.html

It isn't especially Pythonic, but it would allow much easier use of rust-like error-handling code and idioms. Also, people don't need to use those methods if they don't need them.

**Comment by dbrgn** [comment]
Adding `.unwrap` and `.expect` is a good idea. Other methods are less useful in Python, e.g. `unwrap_or(default)` can just be written as `res.ok() or 'default'`.

**Comment by wizzardx** [comment]
.unwrap_or lets you express a function like this:

```python
def parse_int(s, default):
    try:
        i = int(s)
    except ValueError as ex:
        return default
    else:
        return i
```

Like this instead:

```python
def parse_int2(s):
    try:
        i = int(s)
    except ValueError as ex:
        return Err(str(ex))
    else:
        return Ok(i)
```

Which then lets you use parse_int2() in a few Rust-like ways, with less boilerplate than you would need with parse_int().

eg:

```python
i = parse_int2(s).unwrap()
```
or eg:

```python
i = parse_int2(s).expect("Invalid parameter")
```

As well as:

```python
i = parse_int2(s).unwrap_or(123)
```
In addition to the other methods present on in the Result class.

**Comment by dbrgn** [comment]
> As well as:
> 
>     i = parse_int2(s).unwrap_or(123)

That is the same as `i = parse_int2(s).ok() or 123` though, and I'd say that the version with the `or` is easier to read and more pythonic. Don't you think?

**Comment by wizzardx** [comment]
"None" is also a valid return result for a function, so there's eg, a need to be able to do something similar to this:

Assuming that get_item is a wrapper for dict.__item__, except that it returns a Result value, with Ok(val) if the key was present in the dict, or Err("Key not found") if the item is not found (where Python would normally raise an IndexError exception).

If eg, our dict has a value like this: d = dict(test=None)

Then we'd expect git_item('test') to return Ok(None).

And we'd also expect for get_item(d, 'wat') to expect Err("Key not found").

So eg, there is a big difference between these two bits of syntax:

1. i = fetch_item(d, 'test').unwrap_or('DEFAULT')

2. i = fetch_item(d.'test').ok() or 'DEFAULT'

The first one (1) would return None (correct), but the second one would return 'DEFAULT' (incorrect).

A bit more technically/pedantically, it's a bit better to actually have an explicit Option type, rather using None (python) values to always mean the same as Rust's  "None" Enum value.

One big difference between Rust and Python is that Rust doesn't have the concept of None as a valid variable value (it uses Option instead), whereas None is a valid value for any variable. It depends on context whether "None" in Python can mean both "no valid value to return", or eg "string variable has not yet been assigned a string value".

I hope that makes sense.

**Comment by wizzardx** [comment]
Also if ok() returns any other "falsey" value like 0 or False, that would also cause problems.

**Comment by tyehle** [comment]
This is a problem. In this example

```
>>> parsed = parse_int2("0")
>>> parsed
Ok(0)
>>> parsed.ok() or 123
123
```

This should be marked as a bug, not an enhancement.

**Comment by dbrgn** [comment]
You're all right.

I'm a bit busy now, but if someone would want to do a pull request, I'm happy to review and merge.
