### ISSUE TITLE
Add Option type?

### ISSUE THREAD

**Issue by xkortex** [dbrgn/result#43]
Would an Option (Maybe) type (just like Rust) be in scope for a PR for this repo? It's practically the same interface. I know there's `Optional` but you can't map over it :(. I know about [https://github.com/dbrattli/OSlash](OSlash) and [returns](https://github.com/dry-python/returns) but I really like the lightweight interface of this library.

**Comment by francium** [comment]
Have you considered https://github.com/dry-python/returns#maybe-container
I haven't used it myself, but came across it recently, perhaps it may suit you?

Otherwise, not sure if it makes sense to expand this libraries scope, primarily since the name of it is 'result' or make a separate library instead or some other alternative.

**Comment by dbrgn** [comment]
Yeah, I agree about the scope, I'd stick to results.

**Comment by francium** [comment]
@xkortex Feel free to fork if you feel this existing codebase would be a good starting point. Let me know if you need a hand.

**Comment by dbrgn** [comment]
(Also, @francium, if you'd be interested in expanding the scope, I'd be willing to hand over publish access to you. I simply don't have the time to increase the maintenance effort. However, the "result" package name is not ideal if the scope would be expanded, I think having separate pypi packages would be better, even if the two codebases would be in the same repo.)

**Comment by francium** [comment]
@dbrgn sure, let's see how this goes and if there's more interest. This library appears to be slowly gaining more stars if that's any indication of it's usage. Perhaps opening a new organization for this may make sense if it comes to that.

Yes, I'd agree with not expanding the scope of this library at this time.

**Comment by xkortex** [comment]
Yeah, I wouldn't be opposed forking to an Options library, though I think some sort of **PyRustFunctor** would make more sense to leverage overlap. I think there's definitely growing demand as functional python picks up traction. 

@francium would you be interested in such a thing? Gotta check with mgmt but I think they'd be cool with it, I could get the ball rolling and could certainly use a hand if I went that route.

**Comment by francium** [comment]
@xkortex yes, sure, I can help out however I'm able.
